# Dockerfile generated by GeneXus (.NET)
FROM mcr.microsoft.com/dotnet/aspnet:6.0
LABEL maintainer="Karlos <Karlos@example.com>"
WORKDIR /app
COPY ["temp/", "/app"]
ENTRYPOINT ["dotnet", "bin/GxNetCoreStartup.dll"]
